services:
  - type: web
    name: stakemint
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run seed && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
